### ISSUE TITLE
有几个问题和建议

### ISSUE THREAD

**Issue by gregrgr** [kombii/CYAN_EVSE#1]
![image](https://github.com/kombii/CYAN_EVSE/assets/12705933/2f0a5cf5-cafc-49ea-846e-3f0c03047f94)
1、这样采集CP线电压，对CP线电压变化有影响，建议跟随采集后再处理信号。
2、后面那级RC滤波，对快速变化信号，时间太长，会导致动作时间不满足规范（家用无所谓）。
3、CP信号12V和MCU采集控制部分电路要分开，防雷安全性考虑。
4、-12可以不要，不影响通讯。

**Comment by kombii** [comment]
这个项目居然有人回应:)
1.cp线对地（18487的方式3，r2和r3）阻抗是数个k欧，采集这边使用百k级的电阻分压，对于cp线的电压影响是比较小的，规范里对于pwm高电平电压的精度要求是10%左右，影响应该是不会导致兼容性问题的。
2.这个RC滤波的确会降低采样带宽，由于372这一级其实是个峰值保持电路（提取pwm高电平电压），这个延时不仅会体现在最后一级跟随之前，也会体现在这个保持电路上，这个电路在调试时经过测试，从12v转向0v（下降沿比上升要慢很多）需要40ms左右，规范里要求异常情况100ms内断开接触器，这个是可以满足的，不过电压采集的确可以再加速一些，未来会尝试调整。
3.很正确，现在的设计对于防雷这方面的确没有做很完善的设计，会考虑修改。
4.-12v调试时测试过，如果没有，对于大多数新车型都是可以充电的，只有一些比较老的车型，还有特斯拉进口型号会有兼容性问题，这个设计并没有带来太多成本问题，暂时先保留（实际上市面上很多便携充电枪和很大一部分第三方充电桩都没有-12v）

**Comment by gregrgr** [comment]
我也在设计这个，所以你遇到的问题我也遇到过
